language: php
sudo: false
env:
 - TEST_SUITE=common STORAGE_API_TOKEN=$STORAGE_API_TOKEN_MYSQL
 - TEST_SUITE=backend-mysql STORAGE_API_TOKEN=$STORAGE_API_TOKEN_MYSQL
 - TEST_SUITE=backend-redshift STORAGE_API_TOKEN=$STORAGE_API_TOKEN_REDSHIFT
 - TEST_SUITE=backend-snowflake STORAGE_API_TOKEN=$STORAGE_API_TOKEN_SNOWFLAKE
php:
- '5.6'
install:
 - composer install
script:
 - php ./vendor/bin/phpunit --testsuite $TEST_SUITE
