language: php
sudo: false
php:
- '5.6'
install:
 - composer install
script:
 - export STORAGE_API_TOKEN=$STORAGE_API_TOKEN_MYSQL && php ./vendor/bin/phpunit --testsuite common
 - export STORAGE_API_TOKEN=$STORAGE_API_TOKEN_MYSQL && php ./vendor/bin/phpunit --testsuite backend-mysql
 - export STORAGE_API_TOKEN=$STORAGE_API_TOKEN_REDSHIFT && php ./vendor/bin/phpunit --testsuite backend-redshift
 - export STORAGE_API_TOKEN=$STORAGE_API_TOKEN_SNOWFLAKE && php ./vendor/bin/phpunit --testsuite backend-snowflake
